plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 80
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'examples/**/*'

Metrics/ParameterLists:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 200

RSpec/MultipleExpectations:
  Max: 30
